-- Jalankan sekali di SQL Editor proyek Supabase.
-- Gunakan proyek khusus untuk sistem ini agar nama tabel dan kebijakan terpisah.

create table if not exists public.iuran_admins (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.iuran_members (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.iuran_payments (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.iuran_members(id) on delete restrict,
  amount bigint not null check (amount between 1 and 1000000000),
  paid_at date not null,
  note text check (note is null or char_length(note) <= 250),
  created_at timestamptz not null default now()
);

create index if not exists idx_iuran_payments_member on public.iuran_payments(member_id);
create index if not exists idx_iuran_payments_paid_at on public.iuran_payments(paid_at desc);

alter table public.iuran_admins enable row level security;
alter table public.iuran_members enable row level security;
alter table public.iuran_payments enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.iuran_members, public.iuran_payments to anon, authenticated;
grant select on public.iuran_admins to authenticated;
grant insert on public.iuran_members, public.iuran_payments to authenticated;
grant delete on public.iuran_payments to authenticated;

-- Akun yang sedang masuk hanya boleh melihat status pengurus miliknya sendiri.
drop policy if exists "iuran_admins_self_read" on public.iuran_admins;
create policy "iuran_admins_self_read" on public.iuran_admins for select to authenticated
using (id = (select auth.uid()));

-- Rekap dapat dibaca lewat situs tanpa login.
drop policy if exists "iuran_members_read" on public.iuran_members;
create policy "iuran_members_read" on public.iuran_members for select to anon, authenticated using (true);
drop policy if exists "iuran_payments_read" on public.iuran_payments;
create policy "iuran_payments_read" on public.iuran_payments for select to anon, authenticated using (true);

-- Hanya pengurus yang sudah ada dalam iuran_admins boleh mengubah data.
drop policy if exists "iuran_members_insert_admin" on public.iuran_members;
create policy "iuran_members_insert_admin" on public.iuran_members for insert to authenticated
with check (exists (select 1 from public.iuran_admins where id = (select auth.uid())));
drop policy if exists "iuran_payments_insert_admin" on public.iuran_payments;
create policy "iuran_payments_insert_admin" on public.iuran_payments for insert to authenticated
with check (exists (select 1 from public.iuran_admins where id = (select auth.uid())));
drop policy if exists "iuran_payments_delete_admin" on public.iuran_payments;
create policy "iuran_payments_delete_admin" on public.iuran_payments for delete to authenticated
using (exists (select 1 from public.iuran_admins where id = (select auth.uid())));

-- Jalankan perintah ini SETELAH membuat pengurus di Authentication > Users.
-- Ganti email contoh dengan email pengurus yang benar, kemudian jalankan terpisah:
-- insert into public.iuran_admins(id)
-- select id from auth.users where email = 'pengurus@contoh.com'
-- on conflict (id) do nothing;
